type Post {
  body: String!
  owner: User!
  username: String!
}

type User {
  email: String! @unique
  username: String! @unique
  posts: [Post!] @relation
}

type Relationship {
  follower: String!
  following: String!
}

type Query {
  allPosts: [Post!]
}
